import { expect, test } from "@playwright/test";
test("full journey persists outcomes and confirmation refresh never creates another conversion", async ({ page }) => {
  await page.goto("/?measurementDebug=true");
  await page.getByRole("button", { name: "Accept measurement" }).click();
  await page.getByRole("button", { name: "Open local instrumentation log" }).click();
  await expect(page.getByText("Live Pixel is disabled pending official documentation verification.")).toBeVisible();
  await page.getByRole("button", { name: "Close local instrumentation log" }).click();
  await page.getByRole("link", { name: "Explore the collection", exact: false }).first().click();
  await page.getByRole("link", { name: /Aero Run Jacket/ }).click();
  await page.getByRole("button", { name: "Add to bag" }).click();
  await page.getByRole("link", { name: "View bag" }).click();
  await page.getByRole("button", { name: "Increase Aero Run Jacket quantity" }).click();
  await expect(page.getByText("$296.00 USD")).toBeVisible();
  await page.getByRole("button", { name: "Begin demo checkout" }).click();
  await page.getByRole("button", { name: "Complete demo order" }).click();
  await expect(page.getByRole("heading", { name: "You’re ready to move." })).toBeVisible();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("nano-motion-commerce-v1")!));
  expect(saved.order.amount).toBe(29600); expect(saved.cart).toHaveLength(0);
  await page.evaluate(() => history.replaceState(null, "", `${location.pathname}?measurementDebug=true`));
  await page.reload();
  await expect(page.getByRole("heading", { name: "You’re ready to move." })).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("nano-motion-commerce-v1")!).order.id)).toBe(saved.order.id);
  await page.getByRole("button", { name: "Open local instrumentation log" }).click();
  await expect(page.locator(".inspector-panel li").filter({ hasText: "order_created" })).toHaveCount(0);
  await page.getByRole("button", { name: "Close local instrumentation log" }).click();
  await page.getByRole("link", { name: "Find your next advantage with Nano Plus" }).click();
  await page.getByRole("button", { name: "Join demo membership" }).click();
  await expect(page.getByRole("heading", { name: "Welcome to your next chapter." })).toBeVisible();
  const membershipId = await page.evaluate(() => JSON.parse(localStorage.getItem("nano-motion-commerce-v1")!).membership.id);
  await page.evaluate(() => history.replaceState(null, "", `${location.pathname}?measurementDebug=true`));
  await page.reload();
  await expect(page.getByRole("heading", { name: "Welcome to your next chapter." })).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("nano-motion-commerce-v1")!).membership.id)).toBe(membershipId);
});
test("declined consent permits shopping and sends no third-party measurement requests", async ({ page }) => {
  const requests: string[] = []; page.on("request", r => { if (!r.url().startsWith("http://127.0.0.1:3000")) requests.push(r.url()); });
  await page.goto("/product/aero-run-jacket?measurementDebug=true");
  await page.getByRole("button", { name: "Decline", exact: true }).click();
  await page.getByRole("button", { name: "Add to bag" }).click();
  await page.getByRole("button", { name: "Open local instrumentation log" }).click();
  await expect(page.locator(".inspector-panel li").filter({ hasText: "items_added" })).toContainText("suppressed");
  await page.getByRole("button", { name: "Close local instrumentation log" }).click();
  await page.getByRole("link", { name: "View bag" }).click();
  await page.getByRole("button", { name: "Begin demo checkout" }).click();
  await page.getByRole("button", { name: "Complete demo order" }).click();
  await expect(page.getByRole("heading", { name: "You’re ready to move." })).toBeVisible();
  expect(requests).toEqual([]);
});
test("direct confirmation and empty checkout show safe empty states", async ({ page }) => {
  await page.goto("/order-confirmation"); await page.getByRole("button", { name: "Decline", exact: true }).click();
  await expect(page.getByRole("heading", { name: "No order here just yet." })).toBeVisible();
  await page.goto("/membership-confirmation"); await expect(page.getByRole("heading", { name: "Your plus one awaits." })).toBeVisible();
  await page.goto("/checkout"); await expect(page.getByRole("heading", { name: "Your next move awaits." })).toBeVisible();
});
test("checkout refresh reuses attempt and consent reset does not replay conversions", async ({ page }) => {
  await page.goto("/product/aero-run-jacket?measurementDebug=true");
  await page.getByRole("button", { name: "Accept measurement" }).click();
  await page.getByRole("button", { name: "Add to bag" }).click();
  await page.goto("/checkout?measurementDebug=true");
  await expect(page.getByRole("button", { name: "Complete demo order" })).toBeEnabled();
  const attempt = await page.evaluate(() => JSON.parse(localStorage.getItem("nano-motion-commerce-v1")!).attempt.id);
  await page.reload();
  await expect(page.getByRole("button", { name: "Complete demo order" })).toBeEnabled();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("nano-motion-commerce-v1")!).attempt.id)).toBe(attempt);
  await page.getByRole("button", { name: "Open local instrumentation log" }).click();
  await expect(page.locator(".inspector-panel li").filter({ hasText: "checkout_started" })).toHaveCount(0);
  await page.getByRole("button", { name: "Close local instrumentation log" }).click();
  await page.getByRole("button", { name: "Measurement preferences", exact: true }).click();
  await page.getByRole("button", { name: "Decline", exact: true }).click();
  await page.getByRole("button", { name: "Complete demo order" }).click();
  await expect(page.getByRole("heading", { name: "You’re ready to move." })).toBeVisible();
  await page.getByRole("button", { name: "Measurement preferences", exact: true }).click();
  await page.getByRole("button", { name: "Accept measurement" }).click();
  await page.getByRole("button", { name: "Open local instrumentation log" }).click();
  const conversion = page.locator(".inspector-panel li").filter({ hasText: "order_created" });
  await expect(conversion).toHaveCount(1); await expect(conversion).toContainText("suppressed");
});
